.nh
.TH "OPENPASS" "1" "Apr 2026" "OpenPass" "OpenPass Manual"

.SH NAME
openpass-generate-manpages - Generate manual pages


.SH SYNOPSIS
\fBopenpass generate manpages  [flags]\fP


.SH DESCRIPTION
Generate manual pages


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for manpages


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass-generate(1)\fP
