.nh
.TH "OPENPASS" "1" "Apr 2026" "OpenPass" "OpenPass Manual"

.SH NAME
openpass-profile - Manage vault profiles


.SH SYNOPSIS
\fBopenpass profile [flags]\fP


.SH DESCRIPTION
Manage named vault profiles for switching between multiple vaults.

.PP
Examples:
  openpass profile list
  openpass profile add work --vault ~/.openpass-work
  openpass profile use work


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for profile


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP, \fBopenpass-profile-add(1)\fP, \fBopenpass-profile-list(1)\fP, \fBopenpass-profile-use(1)\fP
