.nh
.TH "OPENPASS" "1" "Apr 2026" "OpenPass" "OpenPass Manual"

.SH NAME
openpass - OpenPass is a Go CLI password manager


.SH SYNOPSIS
\fBopenpass [flags]\fP


.SH DESCRIPTION
OpenPass is a Go CLI password manager


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for openpass

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass-add(1)\fP, \fBopenpass-completion(1)\fP, \fBopenpass-delete(1)\fP, \fBopenpass-edit(1)\fP, \fBopenpass-find(1)\fP, \fBopenpass-generate(1)\fP, \fBopenpass-get(1)\fP, \fBopenpass-git(1)\fP, \fBopenpass-init(1)\fP, \fBopenpass-list(1)\fP, \fBopenpass-lock(1)\fP, \fBopenpass-mcp-config(1)\fP, \fBopenpass-mcp-token-rotate(1)\fP, \fBopenpass-recipients(1)\fP, \fBopenpass-serve(1)\fP, \fBopenpass-set(1)\fP, \fBopenpass-unlock(1)\fP, \fBopenpass-version(1)\fP
