.nh
.TH "OPENPASS" "1" "Apr 2026" "OpenPass" "OpenPass Manual"

.SH NAME
openpass-version - Print the version of OpenPass


.SH SYNOPSIS
\fBopenpass version [flags]\fP


.SH DESCRIPTION
Print the version of OpenPass


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
