.nh
.TH "OPENPASS" "1" "Apr 2026" "OpenPass" "OpenPass Manual"

.SH NAME
openpass-delete - Delete a password entry


.SH SYNOPSIS
\fBopenpass delete  [flags]\fP


.SH DESCRIPTION
Delete a password entry


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
